name: authentication-structure-sp
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${USER_DB:-java}
      POSTGRES_PASSWORD: ${USER_PASSWORD:-java}
      POSTGRES_DB: ${NAME_DB:-authentication-sp}
    volumes:
      - ./postgres_data:/data/postgres
    ports:
      - "2345:5432"
    restart: on-failure

volumes:
  postgres_data:
